AWSTemplateFormatVersion: '2010-09-09'
Description: Our app API
Parameters:
  DeploymentStage:
    Description: The stage of this deployment
    Type: String
    Default: development
  Name:
    Description: Name of the RestAPI
    Type: String
    Default: test-api
  SubnetIds:
    Description: SubnetIds of the deployment
    Type: String
  SecurityGroupIds:
    Description: SecurityGroupIds of the deployment
    Type: String
  S3CodeBucket:
    Description: S3CodeBucket of the deployment
    Type: String
Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description:
        Ref: Name
      FailOnWarnings: true
      Name:
        Ref: Name
  UserResource:
    Type: AWS::ApiGateway::Resource
    DependsOn:
      - RestApi
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt
        - RestApi
        - RootResourceId
      PathPart: user
  UserPostTemplate:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - UserResource
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${S3CodeBucket}/user-post.yaml'
      TimeoutInMinutes: 20
      Parameters:
        RestApi: !Ref RestApi
        ResourceId: !Ref UserResource
        SBN: !Ref SubnetIds
        SCG: !Ref SecurityGroupIds
  UserGetTemplate:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - UserResource
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${S3CodeBucket}/user-get.yaml'
      TimeoutInMinutes: 20
      Parameters:
        RestApi: !Ref RestApi
        ResourceId: !Ref UserResource
        SBN: !Ref SubnetIds
        SCG: !Ref SecurityGroupIds
  UserPutTemplate:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - UserResource
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${S3CodeBucket}/user-put.yaml'
      TimeoutInMinutes: 20
      Parameters:
        RestApi: !Ref RestApi
        ResourceId: !Ref UserResource
        SBN: !Ref SubnetIds
        SCG: !Ref SecurityGroupIds
  UserDeleteTemplate:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - UserResource
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${S3CodeBucket}/user-delete.yaml'
      TimeoutInMinutes: 20
      Parameters:
        RestApi: !Ref RestApi
        ResourceId: !Ref UserResource
        SBN: !Ref SubnetIds
        SCG: !Ref SecurityGroupIds
  UserOptionsTemplate:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - UserResource
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${S3CodeBucket}/user-options.yaml'
      TimeoutInMinutes: 20
      Parameters:
        RestApi: !Ref RestApi
        ResourceId: !Ref UserResource
Outputs:
  ServerlessDNS:
    Value:
      Fn::Join:
      - "."
      - - Ref: RestApi
        - execute-api
        - Ref: AWS::Region
        - amazonaws.com
    Description: Serverless DNS
  RestApi:
    Value: !Ref RestApi
    Export:
      Name: RestApi
    Description: RestAPI to use
