AWSTemplateFormatVersion: '2010-09-09'
Description: Our app API
Parameters:
  RestApi:
    Description: Name of the RestAPI
    Type: String
  ResourceId:
    Description: ID of the Resource
    Type: String
  SCG:
    Description: ID of the Resource
    Type: String
  SBN:
    Description: ID of the Resource
    Type: String
Resources:
  UserPutApi:
    Type: AWS::ApiGateway::Method
    DependsOn:
    - UserPutLambda
    Properties:
      HttpMethod: PUT
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
          - lambdaArn: !GetAtt "UserPutLambda.Arn"
      RestApiId: !Ref RestApi
      ResourceId: !Ref ResourceId
  UserPutLambda:
    Type: AWS::Lambda::Function
    DependsOn:
    - UserPutIamRole
    Properties:
      Code: ./
      Description: Function to Get User
      FunctionName: UserPut
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt "UserPutIamRole.Arn"
      Runtime: nodejs10.x
      Timeout: 60
      VpcConfig:
        SecurityGroupIds:
          - !Ref SCG
        SubnetIds:
          - !Ref SBN
  UserPutIamRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: "Allow"
                Resource: '*'
              - Action:
                  - "ec2:CreateNetworkInterface"
                  - "ec2:DescribeNetworkInterfaces"
                  - "ec2:DeleteNetworkInterface"
                Effect: "Allow"
                Resource: '*'
          PolicyName: "UserPutIamRole"
  UserPutApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt "UserPutLambda.Arn"
      Principal: "apigateway.amazonaws.com"
