AWSTemplateFormatVersion: '2010-09-09'
Description: Our app API
Parameters:
  RestApi:
    Description: Name of the RestAPI
    Type: String
  ResourceId:
    Description: ID of the Resource
    Type: String
Resources:
  UserGetApi:
    Type: AWS::ApiGateway::Method
    DependsOn:
    - UserGetLambda
    Properties:
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
          - lambdaArn: !GetAtt "UserGetLambda.Arn"
      RestApiId: !Ref RestApi
      ResourceId: !Ref ResourceId
  UserGetLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: ./
      Description: Function to Get User
      FunctionName: UserGet
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt "UserGetIamRole.Arn"
      Runtime: nodejs10.x
      Timeout: 60
  UserGetIamRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: "Allow"
                Resource: '*'
          PolicyName: "UserGetIamRole"
  UserGetApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt "UserGetLambda.Arn"
      Principal: "apigateway.amazonaws.com"
